# This rule is not used by the project storage-spaces-health-monitor itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to monitor.storage-spaces.monitor.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: storage-spaces-health-monitor
    app.kubernetes.io/managed-by: kustomize
  name: storagespacemonitor-viewer-role
rules:
- apiGroups:
  - monitor.storage-spaces.monitor.com
  resources:
  - storagespacemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.storage-spaces.monitor.com
  resources:
  - storagespacemonitors/status
  verbs:
  - get
